### ISSUE TITLE
TypeError when looking at comments on SubTasks

### ISSUE THREAD

**Issue by Smirl** [alisaifee/jira-cli#14]
When running `jira-cli update TP-20 --comment "New Comment"` or `jira-cli view TP-20 --comments-only` where TP-20 is a subtask, the following error occurs:

```
Traceback (most recent call last):
  File "/Users/alexwilliams/.pyenv/versions/2.7.9/bin/jira-cli", line 9, in <module>
    load_entry_point('jira-cli==2.0.4', 'console_scripts', 'jira-cli')()
  File "/Users/alexwilliams/.pyenv/versions/2.7.9/lib/python2.7/site-packages/jiracli/interface.py", line 227, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/Users/alexwilliams/.pyenv/versions/2.7.9/lib/python2.7/site-packages/jiracli/processor.py", line 23, in execute
    return self.eval()
  File "/Users/alexwilliams/.pyenv/versions/2.7.9/lib/python2.7/site-packages/jiracli/processor.py", line 103, in eval
    print_output(self.jira.format_issue(self.jira.get_issue(self.args.issue), comments_only=True))
  File "/Users/alexwilliams/.pyenv/versions/2.7.9/lib/python2.7/site-packages/jiracli/bridge/__init__.py", line 80, in format_issue
    fields["type"] = JiraBridge.object_from_key(issue["type"], self.get_issue_types)["name"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

*NOTE* - when adding a new comment, the whole command fails but the comment *WILL* be added to the issue.

I see this happening only when the issue is a subtask.

**Comment by alisaifee** [comment]
Fix released in 2.0.5
