### ISSUE TITLE
Unable to use grep on output

### ISSUE THREAD

**Issue by lumberj** [alisaifee/jira-cli#17]
For example:

```
~ » jira-cli list projects | grep RLJS
Traceback (most recent call last):
  File "/usr/local/bin/jira-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/jiracli/interface.py", line 232, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/usr/local/lib/python2.7/site-packages/jiracli/processor.py", line 23, in execute
    return self.eval()
  File "/usr/local/lib/python2.7/site-packages/jiracli/processor.py", line 92, in eval
    val += " [" + colorfunc(item['description'], 'green') + "]"
  File "/usr/local/lib/python2.7/site-packages/jiracli/cli.py", line 25, in <lambda>
    colorfunc = lambda *a,**k:str(a[0])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 727: ordinal not in range(128)
```

This is the relevant problem, https://stackoverflow.com/questions/15739029/python-unicodeencodeerror-when-i-use-grep

I can take a look when I have some time and try to submit a PR

**Comment by alisaifee** [comment]
@lumberj could you please do a quick test whether changing line 25 to `str(a[0]).encode('utf-8')` solves the problem?
