### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by CaptainQuirk** [alisaifee/jira-cli#23]
Hi there,

I installed with __pip__. 

I had to update setuptools with ```easy_install -U setuptools```.
setuptools version seems to be __18.5__ now.

When calling ```jira-cli configure```, I get the following

```
jira-cli configure
Traceback (most recent call last):
  File "/usr/local/bin/jira-cli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 3095, in <module>
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 3081, in _call_aside
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 660, in _build_master
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 673, in _build_from_requirements
  File "build/bdist.macosx-10.11-intel/egg/pkg_resources/__init__.py", line 851, in resolve
pkg_resources.ContextualVersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.
9.0'), set(['jira']))
```

I'm on Mac OS X El Capitan

Thanks in advance

**Comment by alisaifee** [comment]
Seems to be a conflicted version of `six` in your setup (though I'm not able to reproduce the exception you've shown). Could you perhaps try doing a `pip install -U six` and then try again?
