### ISSUE TITLE
updating issue with comment works but prints error

### ISSUE THREAD

**Issue by normn** [alisaifee/jira-cli#35]
On python 2.7.12 and all pip modules freshly updated, I cannot update an issue with a comment.

I can re-assign an issue ok. Am using rest and v2 via defaults. 
```
% jira-cli update CM-2908 --comment test

Traceback (most recent call last):
  File "/usr/bin/jira-cli", line 11, in <module>
    load_entry_point('jira-cli==2.1.4', 'console_scripts', 'jira-cli')()
  File "/usr/lib/python2.7/site-packages/jiracli/interface.py", line 267, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/usr/lib/python2.7/site-packages/jiracli/processor.py", line 26, in execute
    return self.eval()
  File "/usr/lib/python2.7/site-packages/jiracli/processor.py", line 134, in eval
    print_output(self.jira.format_issue(self.jira.get_issue(self.args.issue), comments_only=True))
  File "/usr/lib/python2.7/site-packages/jiracli/bridge/__init__.py", line 80, in format_issue
    self.fields["priority"] = ""
AttributeError: 'JiraRestBridge' object has no attribute 'fields'
```

**Comment by normn** [comment]
My mistake, it does update the issue with the comment, but I still get the above output when running. 

This jira project has no 'priority' field. Maybe it is related to that?
