### ISSUE TITLE
---format does not work: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by Hubbitus** [alisaifee/jira-cli#49]
```bash
$ jira-cli view EG-3743
status               : Open
reporter             : ykovalenko
summary              : ГЛР QA: тестирование расширенного права пользования
assignee             : dushakov
link                 : http://jira.taskdata.com/browse/EG-3743
issue                : EG-3743

$ LANG=C jira-cli view EG-3743 --format="%reporter, %summary, %status"
Traceback (most recent call last):
  File "/usr/bin/jira-cli", line 9, in <module>
    load_entry_point('jira-cli==2.1.5', 'console_scripts', 'jira-cli')()
  File "/usr/lib/python2.7/site-packages/jiracli/interface.py", line 267, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/usr/lib/python2.7/site-packages/jiracli/processor.py", line 27, in execute
    return self.eval()
  File "/usr/lib/python2.7/site-packages/jiracli/processor.py", line 72, in eval
    comments_only=self.args.comments_only
  File "/usr/lib/python2.7/site-packages/jiracli/bridge/__init__.py", line 61, in format_issue
    ret_str = ret_str.replace(k, data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)
```

**Comment by Hubbitus** [comment]
$ jira-cli --version
2.1.5

**Comment by AlJohri** [comment]
@Hubbitus which python version?
