### ISSUE TITLE
python 3 incompatibility: TypeError: unorderable types: NoneType() > int()

### ISSUE THREAD

**Issue by Hubbitus** [alisaifee/jira-cli#50]
```bash
$ jira-cli view --search-jql '"Epic Link" = EG-3769'
Traceback (most recent call last):
  File "/usr/bin/jira-cli", line 9, in <module>
    load_entry_point('jira-cli==2.1.5', 'console_scripts', 'jira-cli')()
  File "/usr/lib/python3.5/site-packages/jiracli/interface.py", line 267, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/usr/lib/python3.5/site-packages/jiracli/processor.py", line 27, in execute
    return self.eval()
  File "/usr/lib/python3.5/site-packages/jiracli/processor.py", line 54, in eval
    elif self.args.verbosity > 1:
TypeError: unorderable types: NoneType() > int()
```

**Comment by AlJohri** [comment]
fixed by #56

**Comment by alisaifee** [comment]
Thanks @AlJohri
