### ISSUE TITLE
Custom columns in search results not supported

### ISSUE THREAD

**Issue by dkindlund** [alisaifee/jira-cli#7]
Hi There,
It seems when I define any sort of custom columns in my JIRA search results, the "jira-cli view --search-jql" command subsequently breaks:

```
Traceback (most recent call last):
  File "/usr/local/bin/jira-cli", line 9, in <module>
    load_entry_point('jira-cli==2.0.1', 'console_scripts', 'jira-cli')()
  File "/Library/Python/2.7/site-packages/jiracli/interface.py", line 217, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/Library/Python/2.7/site-packages/jiracli/processor.py", line 23, in execute
    return self.eval()
  File "/Library/Python/2.7/site-packages/jiracli/processor.py", line 36, in eval
    issues = self.jira.search_issues_jql(self.args.search_jql)
  File "/Library/Python/2.7/site-packages/jiracli/bridge/soap.py", line 135, in search_issues_jql
    return [soap_recursive_dict(k) for k in self.service.getIssuesFromJqlSearch(self.token, query, limit)]
  File "/Library/Python/2.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 661, in process_reply
    replyroot = _parse(reply)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 832, in _parse
    return Parser().parse(string=string)
  File "/Library/Python/2.7/site-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 211, in feed
    self._err_handler.fatalError(exc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
```

It seems like the parser assumes that only the default columns will be in the JIRA search output; you should be able to easily replicate this issue by defining a custom field within your project and then configuring the search interface to show the custom field.

Regards,
-- Darien

**Comment by alisaifee** [comment]
Closing as no update.
