### ISSUE TITLE
jira-cli cannot work well with linux/Mac pipe o/p

### ISSUE THREAD

**Issue by philips-ni** [alisaifee/jira-cli#75]
This is a handy tool!
In Linux/Mac, we use "<command> | grep " a lot to do the filter work.
But while I tried to use jira-cli  to filter the result,  I see this error.

➜  ~ jira-cli list projects|grep -i web
Traceback (most recent call last):
  File "/usr/local/bin/jira-cli", line 11, in <module>
    load_entry_point('jira-cli==2.2', 'console_scripts', 'jira-cli')()
  File "/usr/local/lib/python3.7/site-packages/jiracli/interface.py", line 272, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/usr/local/lib/python3.7/site-packages/jiracli/processor.py", line 30, in execute
    return self.eval()
  File "/usr/local/lib/python3.7/site-packages/jiracli/processor.py", line 121, in eval
    val += " [" + colorfunc(item['key'], 'magenta') + "]"
TypeError: can only concatenate str (not "bytes") to str
➜  ~

**Comment by kyrrigle** [comment]
This is a python3 problem I suspect.   The encode here is returning a bytes that then cannot be concatenated with strings later-

```
color = True
if not sys.stdout.isatty():
    colorfunc = lambda *a,**k:str(a[0]).encode('utf-8')
    color = False
```

a "fix" for that in python3 is to just remove the `.encode('utf-8')` part

**Comment by atsalolikhin-spokeo** [comment]
I tried this on macOS 11 (Big Sur) and couldn't duplicate the issue.  

```
jira-cli list projects|grep -i web
```

This works fine!  No python errors.

I suspect this issue is stale and can be closed.

**Comment by justinabrahms** [comment]
I see this issue on v2.2 and (just upgraded) 3.0. 

It also triggers with output redirection. (e.g. `>` not just `|`)

Using python v3.

**Comment by justinabrahms** [comment]
Heads up, that this fixes it. bridge/__init__.py line ~116

```
            ret_str = colorfunc(issue["key"], status_color).decode('utf-8') + " " + issue.setdefault("summary", "") + " " + url_str.decode('utf-8')
```
