### ISSUE TITLE
Creating new ticket works but crashes when formatting response for cli printing

### ISSUE THREAD

**Issue by jonathankehler** [alisaifee/jira-cli#85]
#jira-cli new --type=FOO --project=BAR "Test ticket"
....
`Traceback (most recent call last):
  File "/home/jonathan/.local/bin/jira-cli", line 8, in <module>
    sys.exit(cli())
  File "/home/jonathan/.local/lib/python2.7/site-packages/jiracli/interface.py", line 272, in cli
    return post_args.cmd(jira, post_args).execute()
  File "/home/jonathan/.local/lib/python2.7/site-packages/jiracli/processor.py", line 30, in execute
    return self.eval()
  File "/home/jonathan/.local/lib/python2.7/site-packages/jiracli/processor.py", line 251, in eval
    self.args.issue_reporter, self.args.labels, components, **extras
  File "/home/jonathan/.local/lib/python2.7/site-packages/jiracli/bridge/__init__.py", line 45, in format_issue
    )["name"]
TypeError: 'NoneType' object has no attribute '__getitem__'
`
I verified the tickets are getting created but its failing when trying to format the issue response.

**Comment by jonathankehler** [comment]
~/.local/lib/python2.7/site-packages/jiracli/bridge/__init__.py - def format_issue,
JiraBridge.object_from_key returns None because the issue number (issue.setdefault('status','1') is not found in the list of statuses (self.get_statuses()).

I'm not sure why yet

**Comment by jonathankehler** [comment]
Yeah its just a mismapping of status id codes. Not sure where is getting self.get_statuses().

**Comment by jonathankehler** [comment]
Meh foxythemes is better sorry
